server:
  port: 8080
spring:
  application:
    name: yuebanhu-tools-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/yuebanhu_tools
    username: nwg
    password: npU#UTXpJWQ3aLkEctrip123
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.jackson.tools.entity

